baseURL = 'https://misfortune.tv'
languageCode = "en-US"
defaultContentLanguage = "en-us"
title = "Misfortune Alert"
theme = "animus"
enableMissingTranslationPlaceholders = true
copyright = "visit <a href='blah'>plasterbrain.com</a>"

[params]
maintenance = true
maintenanceMsg = "Coming Soon"
useAudio = false # Enable sound-playing features

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
		[markup.goldmark.parser.attribute]
			block = true
